from enum import Enum

class ObservableType(str, Enum):
    DOMAIN = "DOMAIN"
    HOSTNAME = "HOSTNAME"
    IP_ADDRESS = "IP_ADDRESS"
    IPV6_ADDRESS = "IPV6_ADDRESS"
    CIDR = "CIDR"
    ASN = "ASN"
    ORGANIZATION = "ORGANIZATION"
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    USERNAME = "USERNAME"
    ACCOUNT = "ACCOUNT"
    URL = "URL"
    CERTIFICATE = "CERTIFICATE"
    RAW_DATA = "RAW_DATA"

class NetworkClass(str, Enum):
    LOCAL_ONLY = "LOCAL_ONLY"
    THIRD_PARTY_ONLY = "THIRD_PARTY_ONLY"
    TARGET_DIRECT = "TARGET_DIRECT"
    TARGET_ACTIVE = "TARGET_ACTIVE"
    PRIVILEGED_LOCAL = "PRIVILEGED_LOCAL"

class ProviderState(str, Enum):
    READY = "READY"
    READY_LIMITED = "READY_LIMITED"
    SUCCESS_NO_FINDINGS = "SUCCESS_NO_FINDINGS"
    DEGRADED = "DEGRADED"
    MISSING_RUNTIME = "MISSING_RUNTIME"
    MISSING_CREDENTIAL = "MISSING_CREDENTIAL"
    RATE_LIMITED = "RATE_LIMITED"
    PARSE_ERROR = "PARSE_ERROR"
    TIMEOUT = "TIMEOUT"
    BROKEN = "BROKEN"
    BLOCKED_LICENSE = "BLOCKED_LICENSE"
    DISABLED = "DISABLED"

class CaseStatus(str, Enum):
    OPEN = "OPEN"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"

class RunStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    PARTIAL = "PARTIAL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class TaskStatus(str, Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"

class AssertionType(str, Enum):
    SUBDOMAIN_OF = "SUBDOMAIN_OF"
    RESOLVES_TO = "RESOLVES_TO"
    BELONGS_TO_ASN = "BELONGS_TO_ASN"
    BELONGS_TO_CIDR = "BELONGS_TO_CIDR"
    HOSTED_ON = "HOSTED_ON"
    OPERATED_BY = "OPERATED_BY"
    BELONGS_TO_DOMAIN = "BELONGS_TO_DOMAIN"
    HAS_MAIL_SERVER = "HAS_MAIL_SERVER"
    HAS_NAMESERVER = "HAS_NAMESERVER"
    SHARES_USERNAME = "SHARES_USERNAME"
    POSSIBLY_SAME_IDENTITY = "POSSIBLY_SAME_IDENTITY"
    ASSOCIATED_WITH = "ASSOCIATED_WITH"
    USES_CERTIFICATE = "USES_CERTIFICATE"
    ALIASED_TO = "ALIASED_TO"


class ExecutionStatus(str, Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"
