from enum import Enum

class ObservableType(str, Enum):
    DOMAIN = "DOMAIN"
    HOSTNAME = "HOSTNAME"
    IP_ADDRESS = "IP_ADDRESS"
    CIDR = "CIDR"
    ASN = "ASN"
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    USERNAME = "USERNAME"
    ACCOUNT = "ACCOUNT"
    URL = "URL"
    CERTIFICATE = "CERTIFICATE"
    ORGANIZATION = "ORGANIZATION"
    UNKNOWN = "UNKNOWN"

class NetworkClass(str, Enum):
    LOCAL_ONLY = "LOCAL_ONLY"
    THIRD_PARTY_ONLY = "THIRD_PARTY_ONLY"
    TARGET_DIRECT = "TARGET_DIRECT"
    TARGET_ACTIVE = "TARGET_ACTIVE"
    PRIVILEGED_LOCAL = "PRIVILEGED_LOCAL"

class ExecutionStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"
    RATE_LIMITED = "RATE_LIMITED"

class ProviderState(str, Enum):
    READY = "READY"
    DEGRADED = "DEGRADED"
    MISSING_CREDENTIAL = "MISSING_CREDENTIAL"
    RATE_LIMITED = "RATE_LIMITED"
    BROKEN = "BROKEN"
    BLOCKED_LICENSE = "BLOCKED_LICENSE"
    DISABLED = "DISABLED"

class AssertionType(str, Enum):
    SAME_AS = "SAME_AS"
    SUBDOMAIN_OF = "SUBDOMAIN_OF"
    RESOLVES_TO = "RESOLVES_TO"
    HOSTED_ON = "HOSTED_ON"
    BELONGS_TO_ASN = "BELONGS_TO_ASN"
    BELONGS_TO_ORG = "BELONGS_TO_ORG"
    ASSOCIATED_WITH_EMAIL = "ASSOCIATED_WITH_EMAIL"
    SHARES_USERNAME = "SHARES_USERNAME"
    POSSIBLY_SAME_IDENTITY = "POSSIBLY_SAME_IDENTITY"
    OBSERVED_ON = "OBSERVED_ON"
    USES_CERTIFICATE = "USES_CERTIFICATE"
    RELATED_INFRASTRUCTURE = "RELATED_INFRASTRUCTURE"
